version: '3'
services:
  db:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  mongo: