name: Ebobot-Workflow
'on':
  push:
    branches:
      - master
jobs:
  build-Ebobot:
    runs-on: ubuntu-latest

    steps:      
      - name: Checkout-Repository
        uses: actions/checkout@v4

      - name: Setup-Golang
        uses: actions/setup-go@v4
        with:
          go-version: '1.22.4'
          check-latest: true
      - run: go version

      - name: Install-Golang-Dependencies
        run: go mod download

      - name: Build-Golang-App
        run: GOOS=linux go build -o build/Ebobot -v

      - name: Display-Build-Golang-App
        run: ls -R build/

      - name: Create-Evn-File
        run: 'echo "DISCORD_TOKEN=${{ secrets.DISCORD_TOKEN }}\nYANDEX_API_KEY=${{ secrets.YANDEX_API_KEY }}\nYANDEX_CATALOG_ID=${{ secrets.YANDEX_CATALOG_ID }}" > build/.env'

      - name: Display-Env-File
        run: cat build/.env

      - name: Copy-Build-Golang-App
        uses: appleboy/scp-action@master
        with:
          host: '${{ secrets.SERVER_HOST }}'
          username: '${{ secrets.SERVER_USERNAME }}'
          key: '${{ secrets.SERVER_SSH_KEY }}'
          port: '${{ secrets.SERVER_SSH_PORT }}'
          source: build/
          target: /var/www/ebobot

      - name: Deploy-Build-Golang-App-To-Server
        uses: appleboy/ssh-action@master
        with:
          host: '${{ secrets.SERVER_HOST }}'
          username: '${{ secrets.SERVER_USERNAME }}'
          key: '${{ secrets.SERVER_SSH_KEY }}'
          port: '${{ secrets.SERVER_SSH_PORT }}'
          script:
            cd /var/www/ebobot
            ls -l
            